### ISSUE TITLE
Feature: create GitHub action to simplify GitHub workflow integration

### ISSUE THREAD

**Issue by laurentsimon** [pypa/pip-audit#198]
**Is your feature request related to a problem? Please describe.**

yes

**Describe the solution you'd like**

It'd be useful to be able to run pip-audit easily in a GitHub workflow (on pull request, or push, on schedule, etc). GitHub actions are used for to create workflows. You can publish the action on the GitHub market place to help users install it at the click of a button.

**Describe alternatives you've considered**

Run the command line and let developers do it themselves. This is more friction.

**Comment by woodruffw** [comment]
Thanks for raising this!

Creating an official GItHub Action for `pip-audit` is on our internal roadmap. We'll keep this issue open to track it publicly as well 🙂 

In the meantime, the folks at Santander have created a third party GitHub Action for `pip-audit` here: https://github.com/Santandersecurityresearch/pip-audit-action

**Comment by artemrys** [comment]
@woodruffw this issue can be closed, as you already released an official GitHub Action (https://github.com/pypa/gh-action-pip-audit).

**Comment by di** [comment]
Thanks @artemrys.
