### ISSUE TITLE
Caching: Use a more respectful default location?

### ISSUE THREAD

**Issue by woodruffw** [pypa/pip-audit#342]
At the moment, we fall back to `~/.pip-audit/cache` if `pip cache dir` fails. This isn't a "respectful" default, since it doesn't adhere to either XDG (which probably wants us to consult `XDG_CACHE_HOME`) or macOS's conventions (`~/Library/Caches`, probably).

This probably isn't the most important change to make since 99% of users won't notice it anyways, but it would make us a slightly better participant in the user's home directory.

**Comment by aanghelidi** [comment]
Hello @woodruffw, I made a PR that solves this issue. It is ready for a review.
