### ISSUE TITLE
Skip vulnerability reports that are marked as "withdrawn"

### ISSUE THREAD

**Issue by woodruffw** [pypa/pip-audit#385]
The OSV format supports the `withdrawn` field, which indicates that a report has been withdrawn and is no longer valid. 

`pip-audit` should respect that field and ignore any reports that contain it, so long as the field's timestamp is not after the current time.

**Comment by woodruffw** [comment]
This applies immediately to the OSV service backend, but may also apply to PyPI's vulnerability DB (which serves a functional subset of the OSV schema). I'll need to check what PyPI's updated does when a entry is marked as withdrawn.

**Comment by woodruffw** [comment]
(I identified this as part of looking into https://github.com/pytest-dev/py/issues/287 -- we "correctly" report this spam vulnerability at the moment because it isn't marked as withdrawn yet, but we should skip it if/when it's correctly withdrawn.)

**Comment by di** [comment]
https://github.com/pypa/pip-audit/pull/386 looks good to me but I think we should probably extend support for this to PyPI as well -- shall we create a separate issue for tracking that?

**Comment by woodruffw** [comment]
Yeah, I think so -- I can create that in a moment.

**Comment by woodruffw** [comment]
#388 is the continuation of this, for PyPI's vulnerability service.
