### ISSUE TITLE
Modernize our type hints

### ISSUE THREAD

**Issue by woodruffw** [pypa/pip-audit#405]
As @orsinium pointed out in #404, we can use more modern type hint styles without needing to increase our minimum Python version.

In particular, we can use type unions (`Foo | Bar`) and "intrinsic" types (`dict[...]` instead of `Dict[...]`).

**Comment by orsinium** [comment]
You can use isort to make annotations lazy (`isort --add-import 'from __future__ import annotations'`) and pyupgrade to use the new style of annotations.

**Comment by orsinium** [comment]
Subscribe to [awesome-python-code-formatters](https://github.com/life4/awesome-python-code-formatters) for more tools 😉

**Comment by woodruffw** [comment]
@jleightcap is going to take a stab at this.
