### ISSUE TITLE
Ability to ignore multiple vulnerabilities

### ISSUE THREAD

**Issue by CribberSix** [pypa/pip-audit#419]
I want to ignore multiple vulnerabilities in my project: 

We are using pyspark=3.2.1 as there is no newer version available on Azure at the moment. If we use `pip-audit` as a pre-commit hook, all of our builds keep failing because there are vulnerabilities for pyspark=3.2.1 - which we need to ignore. 

As far as I figured out, I can only pass single vuln-ids.

**Describe the solution you'd like**
Ability to pass a list of vulnerability IDs to  `pip-audit --ignore-vuln`

e.g.:  `pip-audit --ignore-vuln ['GHSA-4x9r-j582-cgr8', 'PYSEC-2022-42976']`

**Comment by di** [comment]
Reopening this because I think we can improve the help text here.

**Comment by woodruffw** [comment]
Agreed! I'll make a quick PR to improve the `--help` text.
