### ISSUE TITLE
Post-mortem: regression in 2.4.9

### ISSUE THREAD

**Issue by woodruffw** [pypa/pip-audit#441]
We had a regression in 2.4.9, caused by a type error: #439.

In particular, we refactored a file-like type into a `pathlib.Path`, but forgot to update one of the use sites. This _should_ have been caught by `mypy`, so I'm filing this post-mortem to figure out why it wasn't (and what we can do to fix that).

**Comment by woodruffw** [comment]
If I intentionally make `file=` something that definitely can't be written to (like an `int`):

```
        # If our output format is a "manifest" format we always emit it,
        # even if nothing other than a dependency summary is present.
        if skip_count > 0 or formatter.is_manifest:
            with _output_io(args.output) as io:
                foo = 5
                print(formatter.format(result, fixes), file=foo)
```

...then `mypy` fails as expected:

```console
pip_audit/_cli.py:544: error: No overload variant of "print" matches argument types "Any", "int"  [call-overload]
pip_audit/_cli.py:544: note: Possible overload variants:
pip_audit/_cli.py:544: note:     def print(*values: object, sep: Optional[str] = ..., end: Optional[str] = ..., file: Optional[SupportsWrite[str]] = ..., flush: Literal[False] = ...) -> None
pip_audit/_cli.py:544: note:     def print(*values: object, sep: Optional[str] = ..., end: Optional[str] = ..., file: Optional[_SupportsWriteAndFlush[str]] = ..., flush: bool) -> None
Found 1 error in 1 file (checked 28 source files)
make: *** [lint] Error 1
```

...so I'm guessing the issue here is that `mypy` sees `args.output` as an `Any`, given that `args` is just an `argparse.Namespace`. So the resolution here is probably to add more type information to that namespace.

**Comment by woodruffw** [comment]
Looked into this a bit, and there probably isn't a ton we can do here -- `argparse.Namespace` itself is way too dynamic to be typed by `mypy`.

The longer term fix would be to have a custom `Args` or similar class that models the parsed arguments using `pydantic`. But this will require some design consideration, since we make extensive use of argument groups and other `argparse` functionality that will need to be mapped onto a stricter model.

**Comment by jgspiro** [comment]
Surprised flake8 didn't catch the unused variable.  When renaming that variable, flake8 does warn : 

```        if skip_count > 0 or formatter.is_manifest:
            with _output_io(args.output) as io_2:
                print(formatter.format(result, fixes), file=args.output)
```

```
pip_audit/_cli.py:542:45: F841 local variable 'io_2' is assigned to but never used
```

**Comment by woodruffw** [comment]
Upstream: https://github.com/PyCQA/pyflakes/issues/758

**Comment by woodruffw** [comment]
We've switched from `flake8` to `ruff`, but it looks like `ruff` similarly lacks the scope sensitivity needed to correctly catch this bug. So I'll leave this open for the time being.
