### ISSUE TITLE
Separate the linting action into its own GitHub Actions workflow

### ISSUE THREAD

**Issue by woodruffw** [pypa/pip-audit#466]
This is just a reminder to myself: linting failures (which can happen sporadically due to changes imposed by our linting tools) shouldn't cause the entire `CI` workflow to fail/appear red in our README.

**Comment by zafar-hussain** [comment]
Hi @woodruffw,

"continue-on-error: true" under the lint job would work.

I tested it on my fork of pi-audit, although lint was failing, but the workflow passed/appeared green

here is a link to [before and after changes to lint.yml](https://github.com/zafar-hussain/pip-audit/actions) on my fork

Cheers.

**Comment by woodruffw** [comment]
Thanks for the tip @zafar-hussain! This was actually already done with #469, I just forgot to close the associated issue 🙂
