### ISSUE TITLE
Rethink how we handle hashes

### ISSUE THREAD

**Issue by woodruffw** [pypa/pip-audit#516]
This is a breakout from #433, which we attempted to fix in #462.

The problem boils down to this:

1. When a user passes `--require-hashes` or a requirements file that contains hashes, we should disable the dependency resolution machinery: the presence of hashes implies a fully resolved file, so we shouldn't attempt to resolve further.
2. #433 observed that, when a correctly hashed input contains hashes from third-party indices, we fail to check them correctly (since we only check hashes from PyPI, which don't necessarily match)
3. #462 attempted to fix #433 by moving hash checking into the dependency resolution layer, which produced the correct results...
4. ...but regressed overall, since `--require-hashes` no longer skips dependency resolution and instead produces conflicts (#511)

TL;DR: I think we need to entirely rethink how we handle hashes. Some ideas:

1. Move hash checking to its own layer, outside of the vulnerability service layer (pre #462) or dependency layer (post #462). This entails some possible work duplication: we'll probably have to iterate over the requirements again, and make some more (cached) network requests, but it properly preserves the guarantee that hashing disables dependency resolution without locking us into just PyPI's hashes.
2. Loosen our hash checking enforcement: instead of *validating* hashes, we can simply check for their presence and well-formedness. This is "okay" in the sense that `pip-audit` is used in workflows with `pip`, and the latter will actually prevent any hash mismatches from falling through in practice. On the other hand, users may find this confusing (even if it's arguably fine from within our security and use model).

cc @di for thoughts.

**Comment by woodruffw** [comment]
Thinking about this some more: approach (1) wouldn't be too bad if we architect it correctly: we probably want internal `_pep503.py` and `_hashes.py` modules that abstract the indices and hash checking respectively, while reusing our caching middleware. From there, we'd run the hash checking step as a pre-step before anything else.

OTOH, this would still produce a decent slowdown compared to (2) -- we'd still end up fetching a bunch of distributions only to hash and compare them, which would mean that `--require-hashes` would go from "nearly instantaneous" to "roughly as slow as `pip install`.

**Comment by woodruffw** [comment]
And another argument for (2) -- in `--require-hashes` mode we never actually install anything, so *validating* the hashes rather than merely enforcing their presence produces no security properties.

**Comment by tetsuo-cpp** [comment]
You touched on it in another comment but I'm assuming there must be some kind of dependency resolution bug lurking here. I would have thought that even if we fully resolve a hashed requirements file, we'd get back the same set of dependencies that are listed in the requirements file (rather than complain about impossible resolution).

For me, the slowdown is expected since we pushed the hashed requirements path into dependency resolution (although I underestimated how much of a difference that would make) but the fact that we can't even resolve the requirements is a surprise to me.

**Comment by woodruffw** [comment]
Yeah, I think you're right -- this should have just been slow, rather than producing impossible resolutions. So there's likely a separate bug here.

**Comment by woodruffw** [comment]
> So there's likely a separate bug here.

Random guess that just occurred to me: what might be happening is that we resolve `foo==1.2.3`, which produces `bar==1.2.4` as a subdependency. But `bar==1.2.3` is already pinned at the top-level, so we end up with an impossible resolution.

**Comment by tetsuo-cpp** [comment]
> Random guess that just occurred to me: what might be happening is that we resolve `foo==1.2.3`, which produces `bar==1.2.4` as a subdependency. But `bar==1.2.3` is already pinned at the top-level, so we end up with an impossible resolution.

Wouldn't that be impossible to `pip install` though? Or does `pip` just try its best even if it can't satisfy all requirements correctly.

Anyway, it should be easy to do an experiment and figure out what `pip`'s behaviour is.

**Comment by woodruffw** [comment]
> Wouldn't that be impossible to `pip install` though? Or does `pip` just try its best even if it can't satisfy all requirements correctly.

Sorry, this was ambiguous of me -- what I meant is that this is possibly our behavior, not `pip`'s.

In particular, my SWAG is that our backtracking doesn't take top-level requirements into account, only their subdependencies. This is fine in most "normal" requirements inputs, but breaks fully pinned ones because of scenarios like this:

1. Top-level: `foo==1.2.3`, `bar==1.2.3` (from `foo`)
2. Resolve: `foo==1.2.3 -> bar~=1.2 -> bar==1.2.4`
3. Backtrack: `bar==1.2.3`

That's probably what `pip` does, whereas we might be getting caught on (2). I'll investigate to confirm that.

**Comment by tetsuo-cpp** [comment]
As we discussed earlier, we're going to just remove the hash checking logic altogether since `pip` does this already. We'll check that all requirements have a hash but we won't be checking their actual values.

**Comment by tetsuo-cpp** [comment]
The dependency resolution bug that we were discussing is captured in #522.

**Comment by woodruffw** [comment]
With #523 we've pretty much gone back to the original behavior around hash handling.

**Comment by tetsuo-cpp** [comment]
Everything is handled by `pip` now so I don't think there's much to do here anymore.
