### ISSUE TITLE
Figure out how to correctly retrieve dependencies from source distributions

### ISSUE THREAD

**Issue by tetsuo-cpp** [pypa/pip-audit#522]
Our current method of getting dependency requirements for a source distribution is to install it in a virtual environment and then query the list of packages with `pip list`. We then construct a series of requirements that look like: `{package}=={version}`. This is overly restrictive and doesn't capture what the actual requirement is. You can see the code that does that [here](https://github.com/pypa/pip-audit/blob/main/pip_audit/_dependency_source/resolvelib/pypi_provider.py#L221).

For example, a package `foo` might require `bar>=1.0`. When we install into a virtual environment we'll probably install the latest version (let's say that's `bar-3.0`). We'll assume that the requirement is `bar==3.0`. If we later get a package that requires `bar==2.0`, then we'll throw an impossible resolution because we can't satisfy both of these requirements. In reality, we should have just selected `bar-2.0`.

I think that in order to continue with this current approach where we bundle our own resolver, we need to somehow teach `pip-audit` how to find requirements for arbitrary source distributions, similar to what `pip` figures out when you do `pip install .`. This seems difficult as `pip` probably doesn't expose any of this in a way that we can consume as a library.

The other possibility is that we remove the resolver entirely and just lean on `pip` to do everything and do `pip install -r` (and perhaps the new `--dry-run` and `--report` flags) and `pip list` inside a virtual environment.

CC: @woodruffw @jleightcap @di

**Comment by woodruffw** [comment]
> The other possibility is that we remove the resolver entirely and just lean on `pip` to do everything and do `pip install -r` (and perhaps the new `--dry-run` and `--report` flags) and `pip list` inside a virtual environment.

I'm a big fan of switching to this -- IIRC the only real risk/challenge there is that we need to figure out how to make the progress spinner responsive when our resolution step goes from something that we control (with `resolvelib`) to an opaque subprocess.

**Comment by tetsuo-cpp** [comment]
> I'm a big fan of switching to this -- IIRC the only real risk/challenge there is that we need to figure out how to make the progress spinner responsive when our resolution step goes from something that we control (with `resolvelib`) to an opaque subprocess.

Yeah, that could be tricky. I think the solution might be to just let `pip` print it's output since it offers a lot of feedback already. But I imagine we'll have to work around it to stop it from messing with the spinner that we already have.

**Comment by tetsuo-cpp** [comment]
I'm thinking that it might be better to fix this immediately rather than cutting an release in the interim with the hash checking removed. Because even if we fix the issue where dependency resolution is running with hashes, this bug is still really easy to run into now that we're all resolving all dependencies at once as we're meant to.
