### ISSUE TITLE
Could not open requirements file: No such file or directory on Linux

### ISSUE THREAD

**Issue by DariusKunce** [pypa/pip-audit#552]
## Bug description

When `requirements.txt` file has another requirements file referenced inside it with `-r child/component/requirements.txt`, `pip-audit -r requirements.txt` fails.

## Reproduction steps

1. Install pip-audit v2.5.0
2. Create a requirements file for child component at `child/component/requirements.txt` with any dependency.
3. Create a requirements file at project root `requirements.txt`
4. Reference `-r child/component/requirements.txt` inside the `requirements.txt` at root level.
5. Run `pip-audit -r requirements.txt`
6. pip-audit fails:
   ```
   ERROR:pip_audit._virtual_env:internal pip failure: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/child/component/requirements.txt'
   ```

## Expected behavior

No error.

## Screenshots and logs

Log:
```
DEBUG:pip_audit._cli:parsed arguments: Namespace(local=False, requirements=[<_io.TextIOWrapper name='requirements.txt' mode='r' encoding='UTF-8'>], project_path=None, format=<OutputFormatChoice.Columns: 'columns'>, vulnerability_service=<VulnerabilityServiceChoice.Pypi: 'pypi'>, dry_run=False, strict=False, desc=<VulnerabilityDescriptionChoice.Auto: 'auto'>, cache_dir=None, progress_spinner=<ProgressSpinnerChoice.On: 'on'>, timeout=15, paths=[], verbose=1, fix=False, require_hashes=False, index_url='https://pypi.org/simple/', extra_index_urls=[], skip_editable=False, no_deps=False, output=PosixPath('stdout'), ignore_vulns=[])
ERROR:pip_audit._virtual_env:internal pip failure: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/child/component/requirements.txt'

ERROR:pip_audit._cli:Failed to install packages: ['/tmp/tmph391p24m/bin/python', '-m', 'pip', 'install', '--index-url', 'https://pypi.org/simple/', '--dry-run', '--report', '/tmp/tmpxk8qhmm1', '-r', '/tmp/tmp8vdjs_9y']
```

child/component/requirements.txt
```
mypy-boto3-dynamodb >= 1.26.0
```

requirements.txt
```
-r child/component/requirements.txt
```

## Platform information

* OS name and version: 
  Operating System: Amazon Linux 2
  Kernel: Linux 5.4.228-141.415.amzn2int.x86_64
  Architecture: x86-64
* `pip-audit` version (`pip-audit -V`): 
   pip-audit 2.5.0
* Python version (`python -V` or `python3 -V`): 
   Python 3.9.13
* `pip` version (`pip -V` or `pip3 -V`): 
   pip 22.0.4

## Additional context

This started happening after `2.5.0` release on March 16th.  With previous versions there was no error.

**Comment by tetsuo-cpp** [comment]
Hi @DariusKunce, thanks for reporting this.

**Comment by tetsuo-cpp** [comment]
@woodruffw Ah, this is a real headache. I don't think it's practical to copy everything that the input requirements file references into a temporary directory.

My first thought is that maybe we can try to detect when we've been given a process substitution stream (maybe check for a path that looks like `/dev/fd/<n>` ). However, even this doesn't work 100% because the process substitution could reference contain a `-r  blah.txt` line.

Do you have any better ideas?
