### ISSUE TITLE
CLI: add a flag to exit with non-zero code only for fixable vulnerabilities 

### ISSUE THREAD

**Issue by MFTabriz** [pypa/pip-audit#670]
**Is your feature request related to a problem? Please describe.**

When using pip-audit in CI pipelines, there is no point in ~~failing~~ [exiting with non-zero code] for finding unfixable vulnerability in dependencies.

**Describe the solution you'd like**

`--only-fixable` flag (or something similar) to ignore vulnerabilities where no fixed version is available in the database.

**Describe alternatives you've considered**

A solution would be to run `pip-audit`, trap its exit code. If it fails run `pip-audit --fix` and trap its exit code. If it succeeds, `exit 1`. Otherwise, run `diff` on input and output lists and return its exit code.

**Additional context**

I know that I can trap the exit code all together, filter a single vulnerability ID, or set my CI job to allow failure. But as far as I can see, none of them can replicate this exact behavior.

**Comment by woodruffw** [comment]
Thanks for the request @MFTabriz!

Could you say a bit more about your use case here? Are you running `pip-audit --fix` in your CI?

Note that `pip-audit` does not currently "fail" if it can't fix a vulnerability: it exits with a non-zero exit code, but the overall operation completes successfully (in terms of patching what it can). The non-zero exit code is purely there to indicate that something other than "no vulnerabilities found" happened.

If your goal is to ignore runs of `pip-audit --fix` where no changes are made, my (initial) recommendation would be to suppress the exit code entirely and instead check (via `git` or similar) whether `pip-audit` has made any file changes. But I may also be able to offer a better recommendation with more context here 🙂

**Comment by MFTabriz** [comment]
Hi @woodruffw! Thanks for quick response. I edited the issue to distinguish between a non-zero exit code and failing.

I’m running `pip-audit` in a CI job. The goal of this job is to report when a vulnerability in the dependencies is discovered so that the maintainers can update the dependencies. `pip-audit` exists with non-zero code even when there is no fixed version of a vulnerable dependency is available. In these cases usually there is no action by our developers / maintainers is required.

In "Describe alternatives you've considered" section above I just described how that behavior can be "roughly" mimicked.

**Comment by MFTabriz** [comment]
> I _think_ we don't want to change the current behavior here, and we're somewhat conservative about adding new flags at the moment (since each new flag needs to be handled in both "audit" and "fix" modes, and needs to be reconciled with long term `pip` integration goals). That being said, I'm CCing @di here to see if his opinion differs 🙂

I totally get it! If it need too much effort to implement or maintain, there is no point in adding yet another flag.

> In terms of another workaround: have you tried suppressing the error code and parsing the output produced by the `--format=json` option? That output should include whether a fix version is available, meaning that you'll be add some logic to fail the CI job only if a fixable vulnerability is found.

This sounds like a good idea! I’ll give it a try and add my final solution here.

**Comment by di** [comment]
Thanks for the issue!

>  In these cases usually there is no action by our developers / maintainers is required.

Just calling out that one action that _could_ be required in these cases is a downgrade to a version that isn't affected by the vulnerability -- there could be action required, regardless of whether a fix is available.

> I think we don't want to change the current behavior here, and we're somewhat conservative about adding new flags at the moment (since each new flag needs to be handled in both "audit" and "fix" modes, and needs to be reconciled with long term pip integration goals). 

I think I'm in agreement here. Generally I think this library should be noisy when a new vulnerability is found, and allow the user to tune it per vulnerability as necessary (i.e. via `--ignore-vuln`).

That said, I do think there's an interesting edge case when `--ignore-vuln` and `--fix` are used together: right now (I believe) we ignore potential fixes if they're being ignored, but it seems like in your case you might prefer to ignore specific vulnerabilities that haven't been remediated yet, but have `--fix` create fixes for them if/when they are remediated, is that correct?

**Comment by MFTabriz** [comment]
> That said, I do think there's an interesting edge case when `--ignore-vuln` and `--fix` are used together: right now (I believe) we ignore potential fixes if they're being ignored, but it seems like in your case you might prefer to **ignore specific vulnerabilities that haven't been remediated yet, but have `--fix` create fixes for them if/when they are remediated**, is that correct?

Yes! That would be ideal.

**Comment by MFTabriz** [comment]
This needs `jq` to work but should be good enough for most users:

```bash
test -z "$(pip-audit -r requirements.txt --format=json 2>/dev/null | jq '.dependencies[].vulns[].fix_versions[]')"
```

**Comment by woodruffw** [comment]
Thanks for providing that snippet @MFTabriz!

If you're willing, I'd be happy to merge a PR that adds that to a new section under the "Tips and Tricks" part of the README 🙂

**Comment by woodruffw** [comment]
Awesome. If you don't mind submitting that PR, I'll be able to review it today. Otherwise, it'll probably take me a few days to find the time to do it 🙂
