### ISSUE TITLE
html5lib unused?

### ISSUE THREAD

**Issue by 0-wiz-0** [pypa/pip-audit#862]
The html5lib project is not maintained, so I was looking at what used it on my system and found pip-audit:

https://github.com/pypa/pip-audit/blob/72d5a607b90406bd394d54ce8391678b96fc5aa3/pyproject.toml#L32

However, I only get one match in `pyproject.toml`, I don't see an `import html5lib` or anything else referencing it.
Is it really used?

**Comment by woodruffw** [comment]
> Is it really used?

Nope, I think that's a vestigial dep from when `pip-audit` was parsing the PEP 503 index on its own. 

If you're interested in sending a PR to remove that dep, I would be happy to review it :slightly_smiling_face:

**Comment by 0-wiz-0** [comment]
Thanks. My proposed fix is in #863.
